@startuml
namespace modele{
class Observation{
  -String espece
  -String scientific_name
  -Date debut
  -Date fin

  -Scale scale


}
class Feature{
   -float t
   -float b
   -float r
   -float l
   -int nombre_observation

}

class Scale{
   -ArrayList<int> scale
   -ArrayList<PhongMaterial> color


}
class Requete{

  -String scientific_name
  -Date debut
  -Date fin
    
    


    + Observetion sendrequest()
}
class Jsonreader{
      {static}observation readJson(Json fichier)
}
Feature"1"--*"0..n"Observation
Requete"1"--"1"Observation :< "est généré par "
Scale"1"--*"0..n"Observation
}
class view{
  +void display(Observation observation)
}
class controller{
  +Observation sendrequest()
}


@enduml